/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QListWidget *listWidget;
    QLabel *label;
    QPushButton *pushButton;
    QLabel *inpLabel;
    QPushButton *pushButton_2;
    QFrame *mainFrame;
    QLineEdit *mInp2_1;
    QLineEdit *mInp1_2;
    QLineEdit *mInp2_2;
    QLineEdit *mInp1_1;
    QFrame *frame_3;
    QLineEdit *mInp2_3;
    QLineEdit *mInp1_3;
    QLineEdit *mInp3_2;
    QLineEdit *mInp3_1;
    QLineEdit *mInp3_3;
    QFrame *frame_4;
    QLineEdit *mInp4_3;
    QLineEdit *mInp3_4;
    QLineEdit *mInp4_4;
    QLineEdit *mInp2_4;
    QLineEdit *mInp1_4;
    QLineEdit *mInp4_2;
    QLineEdit *mInp4_1;
    QFrame *frame_5;
    QLineEdit *mInp4_5;
    QLineEdit *mInp2_5;
    QLineEdit *mInp1_5;
    QLineEdit *mInp5_2;
    QLineEdit *mInp5_5;
    QLineEdit *mInp5_3;
    QLineEdit *mInp5_1;
    QLineEdit *mInp5_4;
    QLineEdit *mInp3_5;
    QFrame *slidertxtFrame;
    QLabel *inpLabel_5;
    QLabel *inpLabel_4;
    QLabel *inpLabel_3;
    QLabel *inpLabel_2;
    QSlider *mSizeSlider;
    QFrame *ijframe;
    QLabel *label_2;
    QSpinBox *spinBoxI;
    QSpinBox *spinBoxJ;
    QPushButton *saveMatr;
    QLineEdit *ijElemInp;
    QPushButton *readyBut;
    QPushButton *ijSaveBut;
    QPushButton *ijButton;
    QPushButton *ijOutBut;
    QLineEdit *ijElemOut;
    QPushButton *raznBut;
    QPushButton *ravnBut;
    QFrame *rzvFrame;
    QFrame *rzFrame1;
    QLineEdit *rzInp2_1;
    QLineEdit *rzInp1_2;
    QLineEdit *rzInp2_2;
    QLineEdit *rzInp1_1;
    QFrame *rzFrame13;
    QLineEdit *rzInp2_3;
    QLineEdit *rzInp1_3;
    QLineEdit *rzInp3_2;
    QLineEdit *rzInp3_1;
    QLineEdit *rzInp3_3;
    QFrame *rzFrame14;
    QLineEdit *rzInp4_3;
    QLineEdit *rzInp3_4;
    QLineEdit *rzInp4_4;
    QLineEdit *rzInp2_4;
    QLineEdit *rzInp1_4;
    QLineEdit *rzInp4_2;
    QLineEdit *rzInp4_1;
    QFrame *rzFrame15;
    QLineEdit *rzInp4_5;
    QLineEdit *rzInp2_5;
    QLineEdit *rzInp1_5;
    QLineEdit *rzInp5_2;
    QLineEdit *rzInp5_5;
    QLineEdit *rzInp5_3;
    QLineEdit *rzInp5_1;
    QLineEdit *rzInp5_4;
    QLineEdit *rzInp3_5;
    QFrame *rzFrame2;
    QLineEdit *rzInp2_12;
    QLineEdit *rzInp1_22;
    QLineEdit *rzInp2_22;
    QLineEdit *rzInp1_12;
    QFrame *rzFrame23;
    QLineEdit *rzInp2_32;
    QLineEdit *rzInp1_32;
    QLineEdit *rzInp3_22;
    QLineEdit *rzInp3_12;
    QLineEdit *rzInp3_32;
    QFrame *rzFrame24;
    QLineEdit *rzInp4_32;
    QLineEdit *rzInp3_42;
    QLineEdit *rzInp4_42;
    QLineEdit *rzInp2_42;
    QLineEdit *rzInp1_42;
    QLineEdit *rzInp4_22;
    QLineEdit *rzInp4_12;
    QFrame *rzFrame25;
    QLineEdit *rzInp4_52;
    QLineEdit *rzInp2_52;
    QLineEdit *rzInp1_52;
    QLineEdit *rzInp5_22;
    QLineEdit *rzInp5_52;
    QLineEdit *rzInp5_32;
    QLineEdit *rzInp5_12;
    QLineEdit *rzInp5_42;
    QLineEdit *rzInp3_52;
    QLabel *label_4;
    QLabel *label_3;
    QPushButton *rzBut;
    QPushButton *rvBut;
    QLabel *rvLabel;
    QFrame *rzOFrame;
    QLineEdit *rzOut2_1;
    QLineEdit *rzOut1_2;
    QLineEdit *rzOut2_2;
    QLineEdit *rzOut1_1;
    QFrame *rzOFrame3;
    QLineEdit *rzOut2_3;
    QLineEdit *rzOut1_3;
    QLineEdit *rzOut3_2;
    QLineEdit *rzOut3_1;
    QLineEdit *rzOut3_3;
    QFrame *rzOFrame4;
    QLineEdit *rzOut4_3;
    QLineEdit *rzOut3_4;
    QLineEdit *rzOut4_4;
    QLineEdit *rzOut2_4;
    QLineEdit *rzOut1_4;
    QLineEdit *rzOut4_2;
    QLineEdit *rzOut4_1;
    QFrame *rzOFrame5;
    QLineEdit *rzOut4_5;
    QLineEdit *rzOut2_5;
    QLineEdit *rzOut1_5;
    QLineEdit *rzOut5_2;
    QLineEdit *rzOut5_5;
    QLineEdit *rzOut5_3;
    QLineEdit *rzOut5_1;
    QLineEdit *rzOut5_4;
    QLineEdit *rzOut3_5;
    QLabel *rezLabel;
    QPushButton *backButt;
    QFrame *line_2;
    QFrame *line;
    QFrame *line_3;
    QPushButton *clearAllButton;
    QMenuBar *menubar;
    QMenu *menu;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1129, 652);
        MainWindow->setInputMethodHints(Qt::ImhNone);
        MainWindow->setDockOptions(QMainWindow::AllowTabbedDocks|QMainWindow::AnimatedDocks);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        listWidget = new QListWidget(centralwidget);
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        QListWidgetItem *__qlistwidgetitem = new QListWidgetItem(listWidget);
        __qlistwidgetitem->setFont(font);
        __qlistwidgetitem->setFlags(Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        new QListWidgetItem(listWidget);
        QListWidgetItem *__qlistwidgetitem1 = new QListWidgetItem(listWidget);
        __qlistwidgetitem1->setFlags(Qt::ItemIsSelectable|Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled|Qt::ItemIsTristate);
        QListWidgetItem *__qlistwidgetitem2 = new QListWidgetItem(listWidget);
        __qlistwidgetitem2->setFont(font);
        __qlistwidgetitem2->setFlags(Qt::ItemIsDragEnabled|Qt::ItemIsUserCheckable|Qt::ItemIsEnabled);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        new QListWidgetItem(listWidget);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(10, 40, 601, 291));
        QFont font1;
        font1.setPointSize(14);
        listWidget->setFont(font1);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 0, 411, 41));
        QFont font2;
        font2.setPointSize(16);
        label->setFont(font2);
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(250, 430, 110, 30));
        inpLabel = new QLabel(centralwidget);
        inpLabel->setObjectName(QString::fromUtf8("inpLabel"));
        inpLabel->setGeometry(QRect(200, 340, 221, 21));
        QFont font3;
        font3.setPointSize(11);
        inpLabel->setFont(font3);
#if QT_CONFIG(whatsthis)
        inpLabel->setWhatsThis(0u);
#endif // QT_CONFIG(whatsthis)
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(250, 430, 110, 30));
        pushButton_2->setStyleSheet(QString::fromUtf8("background:rgb(85, 85, 255)"));
        mainFrame = new QFrame(centralwidget);
        mainFrame->setObjectName(QString::fromUtf8("mainFrame"));
        mainFrame->setGeometry(QRect(200, 55, 291, 281));
        mainFrame->setFrameShape(QFrame::NoFrame);
        mainFrame->setFrameShadow(QFrame::Raised);
        mInp2_1 = new QLineEdit(mainFrame);
        mInp2_1->setObjectName(QString::fromUtf8("mInp2_1"));
        mInp2_1->setEnabled(false);
        mInp2_1->setGeometry(QRect(2, 57, 50, 50));
        mInp2_1->setMinimumSize(QSize(50, 50));
        mInp2_1->setMaximumSize(QSize(50, 50));
        QFont font4;
        font4.setPointSize(18);
        font4.setItalic(false);
        mInp2_1->setFont(font4);
        mInp2_1->setMaxLength(4);
        mInp2_1->setFrame(true);
        mInp2_1->setCursorPosition(0);
        mInp2_1->setAlignment(Qt::AlignCenter);
        mInp1_2 = new QLineEdit(mainFrame);
        mInp1_2->setObjectName(QString::fromUtf8("mInp1_2"));
        mInp1_2->setGeometry(QRect(57, 2, 50, 50));
        mInp1_2->setMinimumSize(QSize(50, 50));
        mInp1_2->setMaximumSize(QSize(50, 50));
        QFont font5;
        font5.setPointSize(18);
        mInp1_2->setFont(font5);
        mInp1_2->setMaxLength(4);
        mInp1_2->setFrame(true);
        mInp1_2->setCursorPosition(0);
        mInp2_2 = new QLineEdit(mainFrame);
        mInp2_2->setObjectName(QString::fromUtf8("mInp2_2"));
        mInp2_2->setGeometry(QRect(57, 57, 50, 50));
        mInp2_2->setMinimumSize(QSize(50, 50));
        mInp2_2->setMaximumSize(QSize(50, 50));
        mInp2_2->setFont(font5);
        mInp2_2->setMaxLength(4);
        mInp2_2->setFrame(true);
        mInp2_2->setCursorPosition(0);
        mInp1_1 = new QLineEdit(mainFrame);
        mInp1_1->setObjectName(QString::fromUtf8("mInp1_1"));
        mInp1_1->setGeometry(QRect(2, 2, 50, 50));
        mInp1_1->setMinimumSize(QSize(50, 50));
        mInp1_1->setMaximumSize(QSize(50, 50));
        mInp1_1->setFont(font5);
        mInp1_1->setMaxLength(4);
        mInp1_1->setFrame(true);
        mInp1_1->setCursorPosition(0);
        frame_3 = new QFrame(mainFrame);
        frame_3->setObjectName(QString::fromUtf8("frame_3"));
        frame_3->setGeometry(QRect(0, 0, 171, 171));
        mInp2_3 = new QLineEdit(frame_3);
        mInp2_3->setObjectName(QString::fromUtf8("mInp2_3"));
        mInp2_3->setGeometry(QRect(112, 57, 50, 50));
        mInp2_3->setMinimumSize(QSize(50, 50));
        mInp2_3->setMaximumSize(QSize(50, 50));
        mInp2_3->setFont(font5);
        mInp2_3->setMaxLength(4);
        mInp2_3->setFrame(true);
        mInp2_3->setCursorPosition(4);
        mInp1_3 = new QLineEdit(frame_3);
        mInp1_3->setObjectName(QString::fromUtf8("mInp1_3"));
        mInp1_3->setGeometry(QRect(112, 2, 50, 50));
        mInp1_3->setMinimumSize(QSize(50, 50));
        mInp1_3->setMaximumSize(QSize(50, 50));
        mInp1_3->setFont(font5);
        mInp1_3->setMaxLength(4);
        mInp1_3->setFrame(true);
        mInp1_3->setCursorPosition(4);
        mInp3_2 = new QLineEdit(frame_3);
        mInp3_2->setObjectName(QString::fromUtf8("mInp3_2"));
        mInp3_2->setEnabled(false);
        mInp3_2->setGeometry(QRect(57, 112, 50, 50));
        mInp3_2->setMinimumSize(QSize(50, 50));
        mInp3_2->setMaximumSize(QSize(50, 50));
        mInp3_2->setFont(font4);
        mInp3_2->setMaxLength(4);
        mInp3_2->setFrame(true);
        mInp3_2->setCursorPosition(4);
        mInp3_2->setAlignment(Qt::AlignCenter);
        mInp3_1 = new QLineEdit(frame_3);
        mInp3_1->setObjectName(QString::fromUtf8("mInp3_1"));
        mInp3_1->setEnabled(false);
        mInp3_1->setGeometry(QRect(2, 112, 50, 50));
        mInp3_1->setMinimumSize(QSize(50, 50));
        mInp3_1->setMaximumSize(QSize(50, 50));
        mInp3_1->setFont(font4);
        mInp3_1->setMaxLength(4);
        mInp3_1->setFrame(true);
        mInp3_1->setCursorPosition(4);
        mInp3_1->setAlignment(Qt::AlignCenter);
        mInp3_3 = new QLineEdit(frame_3);
        mInp3_3->setObjectName(QString::fromUtf8("mInp3_3"));
        mInp3_3->setGeometry(QRect(112, 112, 50, 50));
        mInp3_3->setMinimumSize(QSize(50, 50));
        mInp3_3->setMaximumSize(QSize(50, 50));
        mInp3_3->setFont(font5);
        mInp3_3->setMaxLength(4);
        mInp3_3->setFrame(true);
        mInp3_3->setCursorPosition(4);
        frame_4 = new QFrame(mainFrame);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(0, 0, 231, 231));
        mInp4_3 = new QLineEdit(frame_4);
        mInp4_3->setObjectName(QString::fromUtf8("mInp4_3"));
        mInp4_3->setEnabled(false);
        mInp4_3->setGeometry(QRect(112, 167, 50, 50));
        mInp4_3->setMinimumSize(QSize(50, 50));
        mInp4_3->setMaximumSize(QSize(50, 50));
        mInp4_3->setFont(font4);
        mInp4_3->setMaxLength(4);
        mInp4_3->setFrame(true);
        mInp4_3->setCursorPosition(0);
        mInp4_3->setAlignment(Qt::AlignCenter);
        mInp3_4 = new QLineEdit(frame_4);
        mInp3_4->setObjectName(QString::fromUtf8("mInp3_4"));
        mInp3_4->setGeometry(QRect(167, 112, 50, 50));
        mInp3_4->setMinimumSize(QSize(50, 50));
        mInp3_4->setMaximumSize(QSize(50, 50));
        mInp3_4->setFont(font5);
        mInp3_4->setMaxLength(4);
        mInp3_4->setFrame(true);
        mInp3_4->setCursorPosition(0);
        mInp4_4 = new QLineEdit(frame_4);
        mInp4_4->setObjectName(QString::fromUtf8("mInp4_4"));
        mInp4_4->setGeometry(QRect(167, 167, 50, 50));
        mInp4_4->setMinimumSize(QSize(50, 50));
        mInp4_4->setMaximumSize(QSize(50, 50));
        mInp4_4->setFont(font5);
        mInp4_4->setMaxLength(4);
        mInp4_4->setFrame(true);
        mInp4_4->setCursorPosition(0);
        mInp2_4 = new QLineEdit(frame_4);
        mInp2_4->setObjectName(QString::fromUtf8("mInp2_4"));
        mInp2_4->setGeometry(QRect(167, 57, 50, 50));
        mInp2_4->setMinimumSize(QSize(50, 50));
        mInp2_4->setMaximumSize(QSize(50, 50));
        mInp2_4->setFont(font5);
        mInp2_4->setMaxLength(4);
        mInp2_4->setFrame(true);
        mInp2_4->setCursorPosition(0);
        mInp1_4 = new QLineEdit(frame_4);
        mInp1_4->setObjectName(QString::fromUtf8("mInp1_4"));
        mInp1_4->setGeometry(QRect(167, 2, 50, 50));
        mInp1_4->setMinimumSize(QSize(50, 50));
        mInp1_4->setMaximumSize(QSize(50, 50));
        mInp1_4->setFont(font5);
        mInp1_4->setMaxLength(4);
        mInp1_4->setFrame(true);
        mInp1_4->setCursorPosition(0);
        mInp4_2 = new QLineEdit(frame_4);
        mInp4_2->setObjectName(QString::fromUtf8("mInp4_2"));
        mInp4_2->setEnabled(false);
        mInp4_2->setGeometry(QRect(57, 167, 50, 50));
        mInp4_2->setMinimumSize(QSize(50, 50));
        mInp4_2->setMaximumSize(QSize(50, 50));
        mInp4_2->setFont(font4);
        mInp4_2->setMaxLength(4);
        mInp4_2->setFrame(true);
        mInp4_2->setCursorPosition(0);
        mInp4_2->setAlignment(Qt::AlignCenter);
        mInp4_1 = new QLineEdit(frame_4);
        mInp4_1->setObjectName(QString::fromUtf8("mInp4_1"));
        mInp4_1->setEnabled(false);
        mInp4_1->setGeometry(QRect(2, 167, 50, 50));
        mInp4_1->setMinimumSize(QSize(50, 50));
        mInp4_1->setMaximumSize(QSize(50, 50));
        mInp4_1->setFont(font4);
        mInp4_1->setMaxLength(4);
        mInp4_1->setFrame(true);
        mInp4_1->setCursorPosition(0);
        mInp4_1->setAlignment(Qt::AlignCenter);
        frame_5 = new QFrame(mainFrame);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(0, 0, 281, 281));
        frame_5->setAutoFillBackground(false);
        mInp4_5 = new QLineEdit(frame_5);
        mInp4_5->setObjectName(QString::fromUtf8("mInp4_5"));
        mInp4_5->setGeometry(QRect(222, 167, 50, 50));
        mInp4_5->setMinimumSize(QSize(50, 50));
        mInp4_5->setMaximumSize(QSize(50, 50));
        mInp4_5->setFont(font5);
        mInp4_5->setMaxLength(4);
        mInp4_5->setFrame(true);
        mInp4_5->setCursorPosition(0);
        mInp2_5 = new QLineEdit(frame_5);
        mInp2_5->setObjectName(QString::fromUtf8("mInp2_5"));
        mInp2_5->setGeometry(QRect(222, 57, 50, 50));
        mInp2_5->setMinimumSize(QSize(50, 50));
        mInp2_5->setMaximumSize(QSize(50, 50));
        mInp2_5->setFont(font5);
        mInp2_5->setMaxLength(4);
        mInp2_5->setFrame(true);
        mInp2_5->setCursorPosition(0);
        mInp1_5 = new QLineEdit(frame_5);
        mInp1_5->setObjectName(QString::fromUtf8("mInp1_5"));
        mInp1_5->setGeometry(QRect(222, 2, 50, 50));
        mInp1_5->setMinimumSize(QSize(50, 50));
        mInp1_5->setMaximumSize(QSize(50, 50));
        mInp1_5->setFont(font5);
        mInp1_5->setMaxLength(4);
        mInp1_5->setFrame(true);
        mInp1_5->setCursorPosition(0);
        mInp5_2 = new QLineEdit(frame_5);
        mInp5_2->setObjectName(QString::fromUtf8("mInp5_2"));
        mInp5_2->setEnabled(false);
        mInp5_2->setGeometry(QRect(57, 222, 50, 50));
        mInp5_2->setMinimumSize(QSize(50, 50));
        mInp5_2->setMaximumSize(QSize(50, 50));
        mInp5_2->setFont(font4);
        mInp5_2->setMaxLength(4);
        mInp5_2->setFrame(true);
        mInp5_2->setCursorPosition(0);
        mInp5_2->setAlignment(Qt::AlignCenter);
        mInp5_5 = new QLineEdit(frame_5);
        mInp5_5->setObjectName(QString::fromUtf8("mInp5_5"));
        mInp5_5->setGeometry(QRect(222, 222, 50, 50));
        mInp5_5->setMinimumSize(QSize(50, 50));
        mInp5_5->setMaximumSize(QSize(50, 50));
        mInp5_5->setFont(font5);
        mInp5_5->setMaxLength(4);
        mInp5_5->setFrame(true);
        mInp5_5->setCursorPosition(0);
        mInp5_3 = new QLineEdit(frame_5);
        mInp5_3->setObjectName(QString::fromUtf8("mInp5_3"));
        mInp5_3->setEnabled(false);
        mInp5_3->setGeometry(QRect(112, 222, 50, 50));
        mInp5_3->setMinimumSize(QSize(50, 50));
        mInp5_3->setMaximumSize(QSize(50, 50));
        mInp5_3->setFont(font4);
        mInp5_3->setMaxLength(4);
        mInp5_3->setFrame(true);
        mInp5_3->setCursorPosition(0);
        mInp5_3->setAlignment(Qt::AlignCenter);
        mInp5_1 = new QLineEdit(frame_5);
        mInp5_1->setObjectName(QString::fromUtf8("mInp5_1"));
        mInp5_1->setEnabled(false);
        mInp5_1->setGeometry(QRect(2, 222, 50, 50));
        mInp5_1->setMinimumSize(QSize(50, 50));
        mInp5_1->setMaximumSize(QSize(50, 50));
        mInp5_1->setFont(font4);
        mInp5_1->setMaxLength(4);
        mInp5_1->setFrame(true);
        mInp5_1->setCursorPosition(0);
        mInp5_1->setAlignment(Qt::AlignCenter);
        mInp5_4 = new QLineEdit(frame_5);
        mInp5_4->setObjectName(QString::fromUtf8("mInp5_4"));
        mInp5_4->setEnabled(false);
        mInp5_4->setGeometry(QRect(167, 222, 50, 50));
        mInp5_4->setMinimumSize(QSize(50, 50));
        mInp5_4->setMaximumSize(QSize(50, 50));
        mInp5_4->setFont(font4);
        mInp5_4->setMaxLength(4);
        mInp5_4->setFrame(true);
        mInp5_4->setCursorPosition(0);
        mInp5_4->setAlignment(Qt::AlignCenter);
        mInp3_5 = new QLineEdit(frame_5);
        mInp3_5->setObjectName(QString::fromUtf8("mInp3_5"));
        mInp3_5->setGeometry(QRect(222, 112, 50, 50));
        mInp3_5->setMinimumSize(QSize(50, 50));
        mInp3_5->setMaximumSize(QSize(50, 50));
        mInp3_5->setFont(font5);
        mInp3_5->setMaxLength(4);
        mInp3_5->setFrame(true);
        mInp3_5->setCursorPosition(0);
        frame_5->raise();
        frame_4->raise();
        frame_3->raise();
        mInp2_1->raise();
        mInp1_2->raise();
        mInp2_2->raise();
        mInp1_1->raise();
        slidertxtFrame = new QFrame(centralwidget);
        slidertxtFrame->setObjectName(QString::fromUtf8("slidertxtFrame"));
        slidertxtFrame->setGeometry(QRect(200, 400, 191, 21));
        slidertxtFrame->setFrameShape(QFrame::StyledPanel);
        slidertxtFrame->setFrameShadow(QFrame::Raised);
        inpLabel_5 = new QLabel(slidertxtFrame);
        inpLabel_5->setObjectName(QString::fromUtf8("inpLabel_5"));
        inpLabel_5->setGeometry(QRect(20, 0, 15, 20));
        QFont font6;
        font6.setPointSize(12);
        inpLabel_5->setFont(font6);
#if QT_CONFIG(whatsthis)
        inpLabel_5->setWhatsThis(0u);
#endif // QT_CONFIG(whatsthis)
        inpLabel_4 = new QLabel(slidertxtFrame);
        inpLabel_4->setObjectName(QString::fromUtf8("inpLabel_4"));
        inpLabel_4->setGeometry(QRect(123, 0, 15, 20));
        inpLabel_4->setFont(font6);
#if QT_CONFIG(whatsthis)
        inpLabel_4->setWhatsThis(0u);
#endif // QT_CONFIG(whatsthis)
        inpLabel_3 = new QLabel(slidertxtFrame);
        inpLabel_3->setObjectName(QString::fromUtf8("inpLabel_3"));
        inpLabel_3->setGeometry(QRect(73, 0, 15, 20));
        inpLabel_3->setFont(font6);
#if QT_CONFIG(whatsthis)
        inpLabel_3->setWhatsThis(0u);
#endif // QT_CONFIG(whatsthis)
        inpLabel_2 = new QLabel(slidertxtFrame);
        inpLabel_2->setObjectName(QString::fromUtf8("inpLabel_2"));
        inpLabel_2->setGeometry(QRect(175, 0, 15, 20));
        inpLabel_2->setFont(font6);
#if QT_CONFIG(whatsthis)
        inpLabel_2->setWhatsThis(0u);
#endif // QT_CONFIG(whatsthis)
        mSizeSlider = new QSlider(centralwidget);
        mSizeSlider->setObjectName(QString::fromUtf8("mSizeSlider"));
        mSizeSlider->setEnabled(true);
        mSizeSlider->setGeometry(QRect(220, 370, 170, 25));
        mSizeSlider->setMinimumSize(QSize(170, 25));
        mSizeSlider->setMaximumSize(QSize(170, 25));
        QFont font7;
        font7.setBold(false);
        font7.setWeight(50);
        font7.setStrikeOut(false);
        font7.setKerning(true);
        mSizeSlider->setFont(font7);
        mSizeSlider->setFocusPolicy(Qt::WheelFocus);
        mSizeSlider->setContextMenuPolicy(Qt::DefaultContextMenu);
        mSizeSlider->setAcceptDrops(false);
        mSizeSlider->setToolTipDuration(-1);
        mSizeSlider->setAutoFillBackground(false);
        mSizeSlider->setStyleSheet(QString::fromUtf8(""));
        mSizeSlider->setInputMethodHints(Qt::ImhNone);
        mSizeSlider->setMinimum(2);
        mSizeSlider->setMaximum(5);
        mSizeSlider->setSingleStep(1);
        mSizeSlider->setPageStep(1);
        mSizeSlider->setValue(2);
        mSizeSlider->setSliderPosition(2);
        mSizeSlider->setTracking(false);
        mSizeSlider->setOrientation(Qt::Horizontal);
        mSizeSlider->setInvertedAppearance(false);
        mSizeSlider->setInvertedControls(true);
        mSizeSlider->setTickPosition(QSlider::TicksBelow);
        mSizeSlider->setTickInterval(1);
        ijframe = new QFrame(centralwidget);
        ijframe->setObjectName(QString::fromUtf8("ijframe"));
        ijframe->setGeometry(QRect(30, 340, 151, 101));
        ijframe->setFrameShape(QFrame::StyledPanel);
        ijframe->setFrameShadow(QFrame::Raised);
        label_2 = new QLabel(ijframe);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(0, 10, 131, 31));
        label_2->setFont(font6);
        spinBoxI = new QSpinBox(ijframe);
        spinBoxI->setObjectName(QString::fromUtf8("spinBoxI"));
        spinBoxI->setGeometry(QRect(10, 50, 50, 32));
        spinBoxI->setFont(font1);
        spinBoxI->setMinimum(1);
        spinBoxI->setMaximum(5);
        spinBoxJ = new QSpinBox(ijframe);
        spinBoxJ->setObjectName(QString::fromUtf8("spinBoxJ"));
        spinBoxJ->setGeometry(QRect(80, 50, 50, 32));
        spinBoxJ->setFont(font1);
        spinBoxJ->setMinimum(1);
        spinBoxJ->setMaximum(5);
        saveMatr = new QPushButton(centralwidget);
        saveMatr->setObjectName(QString::fromUtf8("saveMatr"));
        saveMatr->setGeometry(QRect(260, 480, 91, 31));
        ijElemInp = new QLineEdit(centralwidget);
        ijElemInp->setObjectName(QString::fromUtf8("ijElemInp"));
        ijElemInp->setGeometry(QRect(100, 50, 50, 50));
        ijElemInp->setFont(font5);
        readyBut = new QPushButton(centralwidget);
        readyBut->setObjectName(QString::fromUtf8("readyBut"));
        readyBut->setGeometry(QRect(260, 480, 91, 31));
        ijSaveBut = new QPushButton(centralwidget);
        ijSaveBut->setObjectName(QString::fromUtf8("ijSaveBut"));
        ijSaveBut->setGeometry(QRect(90, 120, 71, 31));
        ijButton = new QPushButton(centralwidget);
        ijButton->setObjectName(QString::fromUtf8("ijButton"));
        ijButton->setGeometry(QRect(50, 450, 80, 21));
        ijOutBut = new QPushButton(centralwidget);
        ijOutBut->setObjectName(QString::fromUtf8("ijOutBut"));
        ijOutBut->setGeometry(QRect(50, 470, 80, 21));
        ijElemOut = new QLineEdit(centralwidget);
        ijElemOut->setObjectName(QString::fromUtf8("ijElemOut"));
        ijElemOut->setGeometry(QRect(210, 50, 50, 50));
        ijElemOut->setFont(font5);
        ijElemOut->setAlignment(Qt::AlignCenter);
        ijElemOut->setReadOnly(true);
        raznBut = new QPushButton(centralwidget);
        raznBut->setObjectName(QString::fromUtf8("raznBut"));
        raznBut->setGeometry(QRect(250, 430, 111, 31));
        raznBut->setStyleSheet(QString::fromUtf8("background:rgb(0, 170, 127)"));
        ravnBut = new QPushButton(centralwidget);
        ravnBut->setObjectName(QString::fromUtf8("ravnBut"));
        ravnBut->setGeometry(QRect(250, 430, 111, 31));
        ravnBut->setStyleSheet(QString::fromUtf8("background: rgb(170, 0, 0)"));
        rzvFrame = new QFrame(centralwidget);
        rzvFrame->setObjectName(QString::fromUtf8("rzvFrame"));
        rzvFrame->setGeometry(QRect(0, 30, 1101, 411));
        rzvFrame->setFrameShape(QFrame::StyledPanel);
        rzvFrame->setFrameShadow(QFrame::Raised);
        rzFrame1 = new QFrame(rzvFrame);
        rzFrame1->setObjectName(QString::fromUtf8("rzFrame1"));
        rzFrame1->setGeometry(QRect(10, 40, 291, 281));
        rzFrame1->setFrameShape(QFrame::NoFrame);
        rzFrame1->setFrameShadow(QFrame::Raised);
        rzInp2_1 = new QLineEdit(rzFrame1);
        rzInp2_1->setObjectName(QString::fromUtf8("rzInp2_1"));
        rzInp2_1->setEnabled(false);
        rzInp2_1->setGeometry(QRect(2, 57, 50, 50));
        rzInp2_1->setMinimumSize(QSize(50, 50));
        rzInp2_1->setMaximumSize(QSize(50, 50));
        rzInp2_1->setFont(font4);
        rzInp2_1->setMaxLength(4);
        rzInp2_1->setFrame(true);
        rzInp2_1->setCursorPosition(0);
        rzInp2_1->setAlignment(Qt::AlignCenter);
        rzInp1_2 = new QLineEdit(rzFrame1);
        rzInp1_2->setObjectName(QString::fromUtf8("rzInp1_2"));
        rzInp1_2->setGeometry(QRect(57, 2, 50, 50));
        rzInp1_2->setMinimumSize(QSize(50, 50));
        rzInp1_2->setMaximumSize(QSize(50, 50));
        rzInp1_2->setFont(font5);
        rzInp1_2->setMaxLength(4);
        rzInp1_2->setFrame(true);
        rzInp1_2->setCursorPosition(0);
        rzInp2_2 = new QLineEdit(rzFrame1);
        rzInp2_2->setObjectName(QString::fromUtf8("rzInp2_2"));
        rzInp2_2->setGeometry(QRect(57, 57, 50, 50));
        rzInp2_2->setMinimumSize(QSize(50, 50));
        rzInp2_2->setMaximumSize(QSize(50, 50));
        rzInp2_2->setFont(font5);
        rzInp2_2->setMaxLength(4);
        rzInp2_2->setFrame(true);
        rzInp2_2->setCursorPosition(0);
        rzInp1_1 = new QLineEdit(rzFrame1);
        rzInp1_1->setObjectName(QString::fromUtf8("rzInp1_1"));
        rzInp1_1->setGeometry(QRect(2, 2, 50, 50));
        rzInp1_1->setMinimumSize(QSize(50, 50));
        rzInp1_1->setMaximumSize(QSize(50, 50));
        rzInp1_1->setFont(font5);
        rzInp1_1->setMaxLength(4);
        rzInp1_1->setFrame(true);
        rzInp1_1->setCursorPosition(0);
        rzFrame13 = new QFrame(rzFrame1);
        rzFrame13->setObjectName(QString::fromUtf8("rzFrame13"));
        rzFrame13->setGeometry(QRect(0, 0, 171, 171));
        rzInp2_3 = new QLineEdit(rzFrame13);
        rzInp2_3->setObjectName(QString::fromUtf8("rzInp2_3"));
        rzInp2_3->setGeometry(QRect(112, 57, 50, 50));
        rzInp2_3->setMinimumSize(QSize(50, 50));
        rzInp2_3->setMaximumSize(QSize(50, 50));
        rzInp2_3->setFont(font5);
        rzInp2_3->setMaxLength(4);
        rzInp2_3->setFrame(true);
        rzInp2_3->setCursorPosition(0);
        rzInp1_3 = new QLineEdit(rzFrame13);
        rzInp1_3->setObjectName(QString::fromUtf8("rzInp1_3"));
        rzInp1_3->setGeometry(QRect(112, 2, 50, 50));
        rzInp1_3->setMinimumSize(QSize(50, 50));
        rzInp1_3->setMaximumSize(QSize(50, 50));
        rzInp1_3->setFont(font5);
        rzInp1_3->setMaxLength(4);
        rzInp1_3->setFrame(true);
        rzInp1_3->setCursorPosition(0);
        rzInp3_2 = new QLineEdit(rzFrame13);
        rzInp3_2->setObjectName(QString::fromUtf8("rzInp3_2"));
        rzInp3_2->setEnabled(false);
        rzInp3_2->setGeometry(QRect(57, 112, 50, 50));
        rzInp3_2->setMinimumSize(QSize(50, 50));
        rzInp3_2->setMaximumSize(QSize(50, 50));
        rzInp3_2->setFont(font4);
        rzInp3_2->setMaxLength(4);
        rzInp3_2->setFrame(true);
        rzInp3_2->setCursorPosition(0);
        rzInp3_2->setAlignment(Qt::AlignCenter);
        rzInp3_1 = new QLineEdit(rzFrame13);
        rzInp3_1->setObjectName(QString::fromUtf8("rzInp3_1"));
        rzInp3_1->setEnabled(false);
        rzInp3_1->setGeometry(QRect(2, 112, 50, 50));
        rzInp3_1->setMinimumSize(QSize(50, 50));
        rzInp3_1->setMaximumSize(QSize(50, 50));
        rzInp3_1->setFont(font4);
        rzInp3_1->setMaxLength(4);
        rzInp3_1->setFrame(true);
        rzInp3_1->setCursorPosition(0);
        rzInp3_1->setAlignment(Qt::AlignCenter);
        rzInp3_3 = new QLineEdit(rzFrame13);
        rzInp3_3->setObjectName(QString::fromUtf8("rzInp3_3"));
        rzInp3_3->setGeometry(QRect(112, 112, 50, 50));
        rzInp3_3->setMinimumSize(QSize(50, 50));
        rzInp3_3->setMaximumSize(QSize(50, 50));
        rzInp3_3->setFont(font5);
        rzInp3_3->setMaxLength(4);
        rzInp3_3->setFrame(true);
        rzInp3_3->setCursorPosition(0);
        rzFrame14 = new QFrame(rzFrame1);
        rzFrame14->setObjectName(QString::fromUtf8("rzFrame14"));
        rzFrame14->setGeometry(QRect(0, 0, 231, 231));
        rzInp4_3 = new QLineEdit(rzFrame14);
        rzInp4_3->setObjectName(QString::fromUtf8("rzInp4_3"));
        rzInp4_3->setEnabled(false);
        rzInp4_3->setGeometry(QRect(112, 167, 50, 50));
        rzInp4_3->setMinimumSize(QSize(50, 50));
        rzInp4_3->setMaximumSize(QSize(50, 50));
        rzInp4_3->setFont(font4);
        rzInp4_3->setMaxLength(4);
        rzInp4_3->setFrame(true);
        rzInp4_3->setCursorPosition(0);
        rzInp4_3->setAlignment(Qt::AlignCenter);
        rzInp3_4 = new QLineEdit(rzFrame14);
        rzInp3_4->setObjectName(QString::fromUtf8("rzInp3_4"));
        rzInp3_4->setGeometry(QRect(167, 112, 50, 50));
        rzInp3_4->setMinimumSize(QSize(50, 50));
        rzInp3_4->setMaximumSize(QSize(50, 50));
        rzInp3_4->setFont(font5);
        rzInp3_4->setMaxLength(4);
        rzInp3_4->setFrame(true);
        rzInp3_4->setCursorPosition(0);
        rzInp4_4 = new QLineEdit(rzFrame14);
        rzInp4_4->setObjectName(QString::fromUtf8("rzInp4_4"));
        rzInp4_4->setGeometry(QRect(167, 167, 50, 50));
        rzInp4_4->setMinimumSize(QSize(50, 50));
        rzInp4_4->setMaximumSize(QSize(50, 50));
        rzInp4_4->setFont(font5);
        rzInp4_4->setMaxLength(4);
        rzInp4_4->setFrame(true);
        rzInp4_4->setCursorPosition(0);
        rzInp2_4 = new QLineEdit(rzFrame14);
        rzInp2_4->setObjectName(QString::fromUtf8("rzInp2_4"));
        rzInp2_4->setGeometry(QRect(167, 57, 50, 50));
        rzInp2_4->setMinimumSize(QSize(50, 50));
        rzInp2_4->setMaximumSize(QSize(50, 50));
        rzInp2_4->setFont(font5);
        rzInp2_4->setMaxLength(4);
        rzInp2_4->setFrame(true);
        rzInp2_4->setCursorPosition(0);
        rzInp1_4 = new QLineEdit(rzFrame14);
        rzInp1_4->setObjectName(QString::fromUtf8("rzInp1_4"));
        rzInp1_4->setGeometry(QRect(167, 2, 50, 50));
        rzInp1_4->setMinimumSize(QSize(50, 50));
        rzInp1_4->setMaximumSize(QSize(50, 50));
        rzInp1_4->setFont(font5);
        rzInp1_4->setMaxLength(4);
        rzInp1_4->setFrame(true);
        rzInp1_4->setCursorPosition(0);
        rzInp4_2 = new QLineEdit(rzFrame14);
        rzInp4_2->setObjectName(QString::fromUtf8("rzInp4_2"));
        rzInp4_2->setEnabled(false);
        rzInp4_2->setGeometry(QRect(57, 167, 50, 50));
        rzInp4_2->setMinimumSize(QSize(50, 50));
        rzInp4_2->setMaximumSize(QSize(50, 50));
        rzInp4_2->setFont(font4);
        rzInp4_2->setMaxLength(4);
        rzInp4_2->setFrame(true);
        rzInp4_2->setCursorPosition(0);
        rzInp4_2->setAlignment(Qt::AlignCenter);
        rzInp4_1 = new QLineEdit(rzFrame14);
        rzInp4_1->setObjectName(QString::fromUtf8("rzInp4_1"));
        rzInp4_1->setEnabled(false);
        rzInp4_1->setGeometry(QRect(2, 167, 50, 50));
        rzInp4_1->setMinimumSize(QSize(50, 50));
        rzInp4_1->setMaximumSize(QSize(50, 50));
        rzInp4_1->setFont(font4);
        rzInp4_1->setMaxLength(4);
        rzInp4_1->setFrame(true);
        rzInp4_1->setCursorPosition(0);
        rzInp4_1->setAlignment(Qt::AlignCenter);
        rzFrame15 = new QFrame(rzFrame1);
        rzFrame15->setObjectName(QString::fromUtf8("rzFrame15"));
        rzFrame15->setGeometry(QRect(0, 0, 281, 281));
        rzFrame15->setAutoFillBackground(false);
        rzInp4_5 = new QLineEdit(rzFrame15);
        rzInp4_5->setObjectName(QString::fromUtf8("rzInp4_5"));
        rzInp4_5->setGeometry(QRect(222, 167, 50, 50));
        rzInp4_5->setMinimumSize(QSize(50, 50));
        rzInp4_5->setMaximumSize(QSize(50, 50));
        rzInp4_5->setFont(font5);
        rzInp4_5->setMaxLength(4);
        rzInp4_5->setFrame(true);
        rzInp4_5->setCursorPosition(0);
        rzInp2_5 = new QLineEdit(rzFrame15);
        rzInp2_5->setObjectName(QString::fromUtf8("rzInp2_5"));
        rzInp2_5->setGeometry(QRect(222, 57, 50, 50));
        rzInp2_5->setMinimumSize(QSize(50, 50));
        rzInp2_5->setMaximumSize(QSize(50, 50));
        rzInp2_5->setFont(font5);
        rzInp2_5->setMaxLength(4);
        rzInp2_5->setFrame(true);
        rzInp2_5->setCursorPosition(0);
        rzInp1_5 = new QLineEdit(rzFrame15);
        rzInp1_5->setObjectName(QString::fromUtf8("rzInp1_5"));
        rzInp1_5->setGeometry(QRect(222, 2, 50, 50));
        rzInp1_5->setMinimumSize(QSize(50, 50));
        rzInp1_5->setMaximumSize(QSize(50, 50));
        rzInp1_5->setFont(font5);
        rzInp1_5->setMaxLength(4);
        rzInp1_5->setFrame(true);
        rzInp1_5->setCursorPosition(0);
        rzInp5_2 = new QLineEdit(rzFrame15);
        rzInp5_2->setObjectName(QString::fromUtf8("rzInp5_2"));
        rzInp5_2->setEnabled(false);
        rzInp5_2->setGeometry(QRect(57, 222, 50, 50));
        rzInp5_2->setMinimumSize(QSize(50, 50));
        rzInp5_2->setMaximumSize(QSize(50, 50));
        rzInp5_2->setFont(font4);
        rzInp5_2->setMaxLength(4);
        rzInp5_2->setFrame(true);
        rzInp5_2->setCursorPosition(0);
        rzInp5_2->setAlignment(Qt::AlignCenter);
        rzInp5_5 = new QLineEdit(rzFrame15);
        rzInp5_5->setObjectName(QString::fromUtf8("rzInp5_5"));
        rzInp5_5->setGeometry(QRect(222, 222, 50, 50));
        rzInp5_5->setMinimumSize(QSize(50, 50));
        rzInp5_5->setMaximumSize(QSize(50, 50));
        rzInp5_5->setFont(font5);
        rzInp5_5->setMaxLength(4);
        rzInp5_5->setFrame(true);
        rzInp5_5->setCursorPosition(0);
        rzInp5_3 = new QLineEdit(rzFrame15);
        rzInp5_3->setObjectName(QString::fromUtf8("rzInp5_3"));
        rzInp5_3->setEnabled(false);
        rzInp5_3->setGeometry(QRect(112, 222, 50, 50));
        rzInp5_3->setMinimumSize(QSize(50, 50));
        rzInp5_3->setMaximumSize(QSize(50, 50));
        rzInp5_3->setFont(font4);
        rzInp5_3->setMaxLength(4);
        rzInp5_3->setFrame(true);
        rzInp5_3->setCursorPosition(0);
        rzInp5_3->setAlignment(Qt::AlignCenter);
        rzInp5_1 = new QLineEdit(rzFrame15);
        rzInp5_1->setObjectName(QString::fromUtf8("rzInp5_1"));
        rzInp5_1->setEnabled(false);
        rzInp5_1->setGeometry(QRect(2, 222, 50, 50));
        rzInp5_1->setMinimumSize(QSize(50, 50));
        rzInp5_1->setMaximumSize(QSize(50, 50));
        rzInp5_1->setFont(font4);
        rzInp5_1->setMaxLength(4);
        rzInp5_1->setFrame(true);
        rzInp5_1->setCursorPosition(0);
        rzInp5_1->setAlignment(Qt::AlignCenter);
        rzInp5_4 = new QLineEdit(rzFrame15);
        rzInp5_4->setObjectName(QString::fromUtf8("rzInp5_4"));
        rzInp5_4->setEnabled(false);
        rzInp5_4->setGeometry(QRect(167, 222, 50, 50));
        rzInp5_4->setMinimumSize(QSize(50, 50));
        rzInp5_4->setMaximumSize(QSize(50, 50));
        rzInp5_4->setFont(font4);
        rzInp5_4->setMaxLength(4);
        rzInp5_4->setFrame(true);
        rzInp5_4->setCursorPosition(0);
        rzInp5_4->setAlignment(Qt::AlignCenter);
        rzInp3_5 = new QLineEdit(rzFrame15);
        rzInp3_5->setObjectName(QString::fromUtf8("rzInp3_5"));
        rzInp3_5->setGeometry(QRect(222, 112, 50, 50));
        rzInp3_5->setMinimumSize(QSize(50, 50));
        rzInp3_5->setMaximumSize(QSize(50, 50));
        rzInp3_5->setFont(font5);
        rzInp3_5->setMaxLength(4);
        rzInp3_5->setFrame(true);
        rzInp3_5->setCursorPosition(0);
        rzFrame15->raise();
        rzFrame14->raise();
        rzFrame13->raise();
        rzInp2_2->raise();
        rzInp1_1->raise();
        rzInp1_2->raise();
        rzInp2_1->raise();
        rzFrame2 = new QFrame(rzvFrame);
        rzFrame2->setObjectName(QString::fromUtf8("rzFrame2"));
        rzFrame2->setGeometry(QRect(380, 40, 291, 281));
        rzFrame2->setFrameShape(QFrame::NoFrame);
        rzFrame2->setFrameShadow(QFrame::Raised);
        rzInp2_12 = new QLineEdit(rzFrame2);
        rzInp2_12->setObjectName(QString::fromUtf8("rzInp2_12"));
        rzInp2_12->setEnabled(false);
        rzInp2_12->setGeometry(QRect(2, 57, 50, 50));
        rzInp2_12->setMinimumSize(QSize(50, 50));
        rzInp2_12->setMaximumSize(QSize(50, 50));
        rzInp2_12->setFont(font4);
        rzInp2_12->setMaxLength(4);
        rzInp2_12->setFrame(true);
        rzInp2_12->setCursorPosition(0);
        rzInp2_12->setAlignment(Qt::AlignCenter);
        rzInp1_22 = new QLineEdit(rzFrame2);
        rzInp1_22->setObjectName(QString::fromUtf8("rzInp1_22"));
        rzInp1_22->setGeometry(QRect(57, 2, 50, 50));
        rzInp1_22->setMinimumSize(QSize(50, 50));
        rzInp1_22->setMaximumSize(QSize(50, 50));
        rzInp1_22->setFont(font5);
        rzInp1_22->setMaxLength(4);
        rzInp1_22->setFrame(true);
        rzInp1_22->setCursorPosition(0);
        rzInp2_22 = new QLineEdit(rzFrame2);
        rzInp2_22->setObjectName(QString::fromUtf8("rzInp2_22"));
        rzInp2_22->setGeometry(QRect(57, 57, 50, 50));
        rzInp2_22->setMinimumSize(QSize(50, 50));
        rzInp2_22->setMaximumSize(QSize(50, 50));
        rzInp2_22->setFont(font5);
        rzInp2_22->setMaxLength(4);
        rzInp2_22->setFrame(true);
        rzInp2_22->setCursorPosition(0);
        rzInp1_12 = new QLineEdit(rzFrame2);
        rzInp1_12->setObjectName(QString::fromUtf8("rzInp1_12"));
        rzInp1_12->setGeometry(QRect(2, 2, 50, 50));
        rzInp1_12->setMinimumSize(QSize(50, 50));
        rzInp1_12->setMaximumSize(QSize(50, 50));
        rzInp1_12->setFont(font5);
        rzInp1_12->setMaxLength(4);
        rzInp1_12->setFrame(true);
        rzInp1_12->setCursorPosition(0);
        rzFrame23 = new QFrame(rzFrame2);
        rzFrame23->setObjectName(QString::fromUtf8("rzFrame23"));
        rzFrame23->setGeometry(QRect(0, 0, 171, 171));
        rzInp2_32 = new QLineEdit(rzFrame23);
        rzInp2_32->setObjectName(QString::fromUtf8("rzInp2_32"));
        rzInp2_32->setGeometry(QRect(112, 57, 50, 50));
        rzInp2_32->setMinimumSize(QSize(50, 50));
        rzInp2_32->setMaximumSize(QSize(50, 50));
        rzInp2_32->setFont(font5);
        rzInp2_32->setMaxLength(4);
        rzInp2_32->setFrame(true);
        rzInp2_32->setCursorPosition(0);
        rzInp1_32 = new QLineEdit(rzFrame23);
        rzInp1_32->setObjectName(QString::fromUtf8("rzInp1_32"));
        rzInp1_32->setGeometry(QRect(112, 2, 50, 50));
        rzInp1_32->setMinimumSize(QSize(50, 50));
        rzInp1_32->setMaximumSize(QSize(50, 50));
        rzInp1_32->setFont(font5);
        rzInp1_32->setMaxLength(4);
        rzInp1_32->setFrame(true);
        rzInp1_32->setCursorPosition(0);
        rzInp3_22 = new QLineEdit(rzFrame23);
        rzInp3_22->setObjectName(QString::fromUtf8("rzInp3_22"));
        rzInp3_22->setEnabled(false);
        rzInp3_22->setGeometry(QRect(57, 112, 50, 50));
        rzInp3_22->setMinimumSize(QSize(50, 50));
        rzInp3_22->setMaximumSize(QSize(50, 50));
        rzInp3_22->setFont(font4);
        rzInp3_22->setMaxLength(4);
        rzInp3_22->setFrame(true);
        rzInp3_22->setCursorPosition(0);
        rzInp3_22->setAlignment(Qt::AlignCenter);
        rzInp3_12 = new QLineEdit(rzFrame23);
        rzInp3_12->setObjectName(QString::fromUtf8("rzInp3_12"));
        rzInp3_12->setEnabled(false);
        rzInp3_12->setGeometry(QRect(2, 112, 50, 50));
        rzInp3_12->setMinimumSize(QSize(50, 50));
        rzInp3_12->setMaximumSize(QSize(50, 50));
        rzInp3_12->setFont(font4);
        rzInp3_12->setMaxLength(4);
        rzInp3_12->setFrame(true);
        rzInp3_12->setCursorPosition(0);
        rzInp3_12->setAlignment(Qt::AlignCenter);
        rzInp3_32 = new QLineEdit(rzFrame23);
        rzInp3_32->setObjectName(QString::fromUtf8("rzInp3_32"));
        rzInp3_32->setGeometry(QRect(112, 112, 50, 50));
        rzInp3_32->setMinimumSize(QSize(50, 50));
        rzInp3_32->setMaximumSize(QSize(50, 50));
        rzInp3_32->setFont(font5);
        rzInp3_32->setMaxLength(4);
        rzInp3_32->setFrame(true);
        rzInp3_32->setCursorPosition(0);
        rzFrame24 = new QFrame(rzFrame2);
        rzFrame24->setObjectName(QString::fromUtf8("rzFrame24"));
        rzFrame24->setGeometry(QRect(0, 0, 231, 231));
        rzInp4_32 = new QLineEdit(rzFrame24);
        rzInp4_32->setObjectName(QString::fromUtf8("rzInp4_32"));
        rzInp4_32->setEnabled(false);
        rzInp4_32->setGeometry(QRect(112, 167, 50, 50));
        rzInp4_32->setMinimumSize(QSize(50, 50));
        rzInp4_32->setMaximumSize(QSize(50, 50));
        rzInp4_32->setFont(font4);
        rzInp4_32->setMaxLength(4);
        rzInp4_32->setFrame(true);
        rzInp4_32->setCursorPosition(0);
        rzInp4_32->setAlignment(Qt::AlignCenter);
        rzInp3_42 = new QLineEdit(rzFrame24);
        rzInp3_42->setObjectName(QString::fromUtf8("rzInp3_42"));
        rzInp3_42->setGeometry(QRect(167, 112, 50, 50));
        rzInp3_42->setMinimumSize(QSize(50, 50));
        rzInp3_42->setMaximumSize(QSize(50, 50));
        rzInp3_42->setFont(font5);
        rzInp3_42->setMaxLength(4);
        rzInp3_42->setFrame(true);
        rzInp3_42->setCursorPosition(0);
        rzInp4_42 = new QLineEdit(rzFrame24);
        rzInp4_42->setObjectName(QString::fromUtf8("rzInp4_42"));
        rzInp4_42->setGeometry(QRect(167, 167, 50, 50));
        rzInp4_42->setMinimumSize(QSize(50, 50));
        rzInp4_42->setMaximumSize(QSize(50, 50));
        rzInp4_42->setFont(font5);
        rzInp4_42->setMaxLength(4);
        rzInp4_42->setFrame(true);
        rzInp4_42->setCursorPosition(0);
        rzInp2_42 = new QLineEdit(rzFrame24);
        rzInp2_42->setObjectName(QString::fromUtf8("rzInp2_42"));
        rzInp2_42->setGeometry(QRect(167, 57, 50, 50));
        rzInp2_42->setMinimumSize(QSize(50, 50));
        rzInp2_42->setMaximumSize(QSize(50, 50));
        rzInp2_42->setFont(font5);
        rzInp2_42->setMaxLength(4);
        rzInp2_42->setFrame(true);
        rzInp2_42->setCursorPosition(0);
        rzInp1_42 = new QLineEdit(rzFrame24);
        rzInp1_42->setObjectName(QString::fromUtf8("rzInp1_42"));
        rzInp1_42->setGeometry(QRect(167, 2, 50, 50));
        rzInp1_42->setMinimumSize(QSize(50, 50));
        rzInp1_42->setMaximumSize(QSize(50, 50));
        rzInp1_42->setFont(font5);
        rzInp1_42->setMaxLength(4);
        rzInp1_42->setFrame(true);
        rzInp1_42->setCursorPosition(0);
        rzInp4_22 = new QLineEdit(rzFrame24);
        rzInp4_22->setObjectName(QString::fromUtf8("rzInp4_22"));
        rzInp4_22->setEnabled(false);
        rzInp4_22->setGeometry(QRect(57, 167, 50, 50));
        rzInp4_22->setMinimumSize(QSize(50, 50));
        rzInp4_22->setMaximumSize(QSize(50, 50));
        rzInp4_22->setFont(font4);
        rzInp4_22->setMaxLength(4);
        rzInp4_22->setFrame(true);
        rzInp4_22->setCursorPosition(0);
        rzInp4_22->setAlignment(Qt::AlignCenter);
        rzInp4_12 = new QLineEdit(rzFrame24);
        rzInp4_12->setObjectName(QString::fromUtf8("rzInp4_12"));
        rzInp4_12->setEnabled(false);
        rzInp4_12->setGeometry(QRect(2, 167, 50, 50));
        rzInp4_12->setMinimumSize(QSize(50, 50));
        rzInp4_12->setMaximumSize(QSize(50, 50));
        rzInp4_12->setFont(font4);
        rzInp4_12->setMaxLength(4);
        rzInp4_12->setFrame(true);
        rzInp4_12->setCursorPosition(0);
        rzInp4_12->setAlignment(Qt::AlignCenter);
        rzFrame25 = new QFrame(rzFrame2);
        rzFrame25->setObjectName(QString::fromUtf8("rzFrame25"));
        rzFrame25->setGeometry(QRect(0, 0, 281, 281));
        rzFrame25->setAutoFillBackground(false);
        rzInp4_52 = new QLineEdit(rzFrame25);
        rzInp4_52->setObjectName(QString::fromUtf8("rzInp4_52"));
        rzInp4_52->setGeometry(QRect(222, 167, 50, 50));
        rzInp4_52->setMinimumSize(QSize(50, 50));
        rzInp4_52->setMaximumSize(QSize(50, 50));
        rzInp4_52->setFont(font5);
        rzInp4_52->setMaxLength(4);
        rzInp4_52->setFrame(true);
        rzInp4_52->setCursorPosition(0);
        rzInp2_52 = new QLineEdit(rzFrame25);
        rzInp2_52->setObjectName(QString::fromUtf8("rzInp2_52"));
        rzInp2_52->setGeometry(QRect(222, 57, 50, 50));
        rzInp2_52->setMinimumSize(QSize(50, 50));
        rzInp2_52->setMaximumSize(QSize(50, 50));
        rzInp2_52->setFont(font5);
        rzInp2_52->setMaxLength(4);
        rzInp2_52->setFrame(true);
        rzInp2_52->setCursorPosition(0);
        rzInp1_52 = new QLineEdit(rzFrame25);
        rzInp1_52->setObjectName(QString::fromUtf8("rzInp1_52"));
        rzInp1_52->setGeometry(QRect(222, 2, 50, 50));
        rzInp1_52->setMinimumSize(QSize(50, 50));
        rzInp1_52->setMaximumSize(QSize(50, 50));
        rzInp1_52->setFont(font5);
        rzInp1_52->setMaxLength(4);
        rzInp1_52->setFrame(true);
        rzInp1_52->setCursorPosition(0);
        rzInp5_22 = new QLineEdit(rzFrame25);
        rzInp5_22->setObjectName(QString::fromUtf8("rzInp5_22"));
        rzInp5_22->setEnabled(false);
        rzInp5_22->setGeometry(QRect(57, 222, 50, 50));
        rzInp5_22->setMinimumSize(QSize(50, 50));
        rzInp5_22->setMaximumSize(QSize(50, 50));
        rzInp5_22->setFont(font4);
        rzInp5_22->setMaxLength(4);
        rzInp5_22->setFrame(true);
        rzInp5_22->setCursorPosition(0);
        rzInp5_22->setAlignment(Qt::AlignCenter);
        rzInp5_52 = new QLineEdit(rzFrame25);
        rzInp5_52->setObjectName(QString::fromUtf8("rzInp5_52"));
        rzInp5_52->setGeometry(QRect(222, 222, 50, 50));
        rzInp5_52->setMinimumSize(QSize(50, 50));
        rzInp5_52->setMaximumSize(QSize(50, 50));
        rzInp5_52->setFont(font5);
        rzInp5_52->setMaxLength(4);
        rzInp5_52->setFrame(true);
        rzInp5_52->setCursorPosition(0);
        rzInp5_32 = new QLineEdit(rzFrame25);
        rzInp5_32->setObjectName(QString::fromUtf8("rzInp5_32"));
        rzInp5_32->setEnabled(false);
        rzInp5_32->setGeometry(QRect(112, 222, 50, 50));
        rzInp5_32->setMinimumSize(QSize(50, 50));
        rzInp5_32->setMaximumSize(QSize(50, 50));
        rzInp5_32->setFont(font4);
        rzInp5_32->setMaxLength(4);
        rzInp5_32->setFrame(true);
        rzInp5_32->setCursorPosition(0);
        rzInp5_32->setAlignment(Qt::AlignCenter);
        rzInp5_12 = new QLineEdit(rzFrame25);
        rzInp5_12->setObjectName(QString::fromUtf8("rzInp5_12"));
        rzInp5_12->setEnabled(false);
        rzInp5_12->setGeometry(QRect(2, 222, 50, 50));
        rzInp5_12->setMinimumSize(QSize(50, 50));
        rzInp5_12->setMaximumSize(QSize(50, 50));
        rzInp5_12->setFont(font4);
        rzInp5_12->setMaxLength(4);
        rzInp5_12->setFrame(true);
        rzInp5_12->setCursorPosition(0);
        rzInp5_12->setAlignment(Qt::AlignCenter);
        rzInp5_42 = new QLineEdit(rzFrame25);
        rzInp5_42->setObjectName(QString::fromUtf8("rzInp5_42"));
        rzInp5_42->setEnabled(false);
        rzInp5_42->setGeometry(QRect(167, 222, 50, 50));
        rzInp5_42->setMinimumSize(QSize(50, 50));
        rzInp5_42->setMaximumSize(QSize(50, 50));
        rzInp5_42->setFont(font4);
        rzInp5_42->setMaxLength(4);
        rzInp5_42->setFrame(true);
        rzInp5_42->setCursorPosition(0);
        rzInp5_42->setAlignment(Qt::AlignCenter);
        rzInp3_52 = new QLineEdit(rzFrame25);
        rzInp3_52->setObjectName(QString::fromUtf8("rzInp3_52"));
        rzInp3_52->setGeometry(QRect(222, 112, 50, 50));
        rzInp3_52->setMinimumSize(QSize(50, 50));
        rzInp3_52->setMaximumSize(QSize(50, 50));
        rzInp3_52->setFont(font5);
        rzInp3_52->setMaxLength(4);
        rzInp3_52->setFrame(true);
        rzInp3_52->setCursorPosition(0);
        rzFrame25->raise();
        rzFrame24->raise();
        rzFrame23->raise();
        rzInp1_12->raise();
        rzInp1_22->raise();
        rzInp2_12->raise();
        rzInp2_22->raise();
        label_4 = new QLabel(rzvFrame);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(380, 0, 241, 31));
        label_4->setFont(font1);
        label_3 = new QLabel(rzvFrame);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 0, 241, 31));
        label_3->setFont(font1);
        rzBut = new QPushButton(rzvFrame);
        rzBut->setObjectName(QString::fromUtf8("rzBut"));
        rzBut->setGeometry(QRect(290, 370, 91, 31));
        rvBut = new QPushButton(rzvFrame);
        rvBut->setObjectName(QString::fromUtf8("rvBut"));
        rvBut->setGeometry(QRect(290, 370, 91, 31));
        rvLabel = new QLabel(rzvFrame);
        rvLabel->setObjectName(QString::fromUtf8("rvLabel"));
        rvLabel->setGeometry(QRect(260, 330, 201, 31));
        rvLabel->setFont(font2);
        rzOFrame = new QFrame(rzvFrame);
        rzOFrame->setObjectName(QString::fromUtf8("rzOFrame"));
        rzOFrame->setGeometry(QRect(760, 40, 291, 281));
        rzOFrame->setFrameShape(QFrame::NoFrame);
        rzOFrame->setFrameShadow(QFrame::Raised);
        rzOut2_1 = new QLineEdit(rzOFrame);
        rzOut2_1->setObjectName(QString::fromUtf8("rzOut2_1"));
        rzOut2_1->setEnabled(false);
        rzOut2_1->setGeometry(QRect(2, 57, 50, 50));
        rzOut2_1->setMinimumSize(QSize(50, 50));
        rzOut2_1->setMaximumSize(QSize(50, 50));
        rzOut2_1->setFont(font4);
        rzOut2_1->setMaxLength(4);
        rzOut2_1->setFrame(true);
        rzOut2_1->setCursorPosition(0);
        rzOut2_1->setAlignment(Qt::AlignCenter);
        rzOut1_2 = new QLineEdit(rzOFrame);
        rzOut1_2->setObjectName(QString::fromUtf8("rzOut1_2"));
        rzOut1_2->setGeometry(QRect(57, 2, 50, 50));
        rzOut1_2->setMinimumSize(QSize(50, 50));
        rzOut1_2->setMaximumSize(QSize(50, 50));
        rzOut1_2->setFont(font5);
        rzOut1_2->setMaxLength(4);
        rzOut1_2->setFrame(true);
        rzOut1_2->setCursorPosition(0);
        rzOut1_2->setReadOnly(true);
        rzOut2_2 = new QLineEdit(rzOFrame);
        rzOut2_2->setObjectName(QString::fromUtf8("rzOut2_2"));
        rzOut2_2->setGeometry(QRect(57, 57, 50, 50));
        rzOut2_2->setMinimumSize(QSize(50, 50));
        rzOut2_2->setMaximumSize(QSize(50, 50));
        rzOut2_2->setFont(font5);
        rzOut2_2->setMaxLength(4);
        rzOut2_2->setFrame(true);
        rzOut2_2->setCursorPosition(0);
        rzOut2_2->setReadOnly(true);
        rzOut1_1 = new QLineEdit(rzOFrame);
        rzOut1_1->setObjectName(QString::fromUtf8("rzOut1_1"));
        rzOut1_1->setGeometry(QRect(2, 2, 50, 50));
        rzOut1_1->setMinimumSize(QSize(50, 50));
        rzOut1_1->setMaximumSize(QSize(50, 50));
        rzOut1_1->setFont(font5);
        rzOut1_1->setMaxLength(4);
        rzOut1_1->setFrame(true);
        rzOut1_1->setCursorPosition(0);
        rzOut1_1->setReadOnly(true);
        rzOFrame3 = new QFrame(rzOFrame);
        rzOFrame3->setObjectName(QString::fromUtf8("rzOFrame3"));
        rzOFrame3->setGeometry(QRect(0, 0, 171, 171));
        rzOut2_3 = new QLineEdit(rzOFrame3);
        rzOut2_3->setObjectName(QString::fromUtf8("rzOut2_3"));
        rzOut2_3->setGeometry(QRect(112, 57, 50, 50));
        rzOut2_3->setMinimumSize(QSize(50, 50));
        rzOut2_3->setMaximumSize(QSize(50, 50));
        rzOut2_3->setFont(font5);
        rzOut2_3->setMaxLength(4);
        rzOut2_3->setFrame(true);
        rzOut2_3->setCursorPosition(0);
        rzOut2_3->setReadOnly(true);
        rzOut1_3 = new QLineEdit(rzOFrame3);
        rzOut1_3->setObjectName(QString::fromUtf8("rzOut1_3"));
        rzOut1_3->setGeometry(QRect(112, 2, 50, 50));
        rzOut1_3->setMinimumSize(QSize(50, 50));
        rzOut1_3->setMaximumSize(QSize(50, 50));
        rzOut1_3->setFont(font5);
        rzOut1_3->setMaxLength(4);
        rzOut1_3->setFrame(true);
        rzOut1_3->setCursorPosition(0);
        rzOut1_3->setReadOnly(true);
        rzOut3_2 = new QLineEdit(rzOFrame3);
        rzOut3_2->setObjectName(QString::fromUtf8("rzOut3_2"));
        rzOut3_2->setEnabled(false);
        rzOut3_2->setGeometry(QRect(57, 112, 50, 50));
        rzOut3_2->setMinimumSize(QSize(50, 50));
        rzOut3_2->setMaximumSize(QSize(50, 50));
        rzOut3_2->setFont(font4);
        rzOut3_2->setMaxLength(4);
        rzOut3_2->setFrame(true);
        rzOut3_2->setCursorPosition(0);
        rzOut3_2->setAlignment(Qt::AlignCenter);
        rzOut3_1 = new QLineEdit(rzOFrame3);
        rzOut3_1->setObjectName(QString::fromUtf8("rzOut3_1"));
        rzOut3_1->setEnabled(false);
        rzOut3_1->setGeometry(QRect(2, 112, 50, 50));
        rzOut3_1->setMinimumSize(QSize(50, 50));
        rzOut3_1->setMaximumSize(QSize(50, 50));
        rzOut3_1->setFont(font4);
        rzOut3_1->setMaxLength(4);
        rzOut3_1->setFrame(true);
        rzOut3_1->setCursorPosition(0);
        rzOut3_1->setAlignment(Qt::AlignCenter);
        rzOut3_3 = new QLineEdit(rzOFrame3);
        rzOut3_3->setObjectName(QString::fromUtf8("rzOut3_3"));
        rzOut3_3->setGeometry(QRect(112, 112, 50, 50));
        rzOut3_3->setMinimumSize(QSize(50, 50));
        rzOut3_3->setMaximumSize(QSize(50, 50));
        rzOut3_3->setFont(font5);
        rzOut3_3->setMaxLength(4);
        rzOut3_3->setFrame(true);
        rzOut3_3->setCursorPosition(0);
        rzOut3_3->setReadOnly(true);
        rzOFrame4 = new QFrame(rzOFrame);
        rzOFrame4->setObjectName(QString::fromUtf8("rzOFrame4"));
        rzOFrame4->setGeometry(QRect(0, 0, 231, 231));
        rzOut4_3 = new QLineEdit(rzOFrame4);
        rzOut4_3->setObjectName(QString::fromUtf8("rzOut4_3"));
        rzOut4_3->setEnabled(false);
        rzOut4_3->setGeometry(QRect(112, 167, 50, 50));
        rzOut4_3->setMinimumSize(QSize(50, 50));
        rzOut4_3->setMaximumSize(QSize(50, 50));
        rzOut4_3->setFont(font4);
        rzOut4_3->setMaxLength(4);
        rzOut4_3->setFrame(true);
        rzOut4_3->setCursorPosition(0);
        rzOut4_3->setAlignment(Qt::AlignCenter);
        rzOut3_4 = new QLineEdit(rzOFrame4);
        rzOut3_4->setObjectName(QString::fromUtf8("rzOut3_4"));
        rzOut3_4->setGeometry(QRect(167, 112, 50, 50));
        rzOut3_4->setMinimumSize(QSize(50, 50));
        rzOut3_4->setMaximumSize(QSize(50, 50));
        rzOut3_4->setFont(font5);
        rzOut3_4->setMaxLength(4);
        rzOut3_4->setFrame(true);
        rzOut3_4->setCursorPosition(0);
        rzOut3_4->setReadOnly(true);
        rzOut4_4 = new QLineEdit(rzOFrame4);
        rzOut4_4->setObjectName(QString::fromUtf8("rzOut4_4"));
        rzOut4_4->setGeometry(QRect(167, 167, 50, 50));
        rzOut4_4->setMinimumSize(QSize(50, 50));
        rzOut4_4->setMaximumSize(QSize(50, 50));
        rzOut4_4->setFont(font5);
        rzOut4_4->setMaxLength(4);
        rzOut4_4->setFrame(true);
        rzOut4_4->setCursorPosition(0);
        rzOut4_4->setReadOnly(true);
        rzOut2_4 = new QLineEdit(rzOFrame4);
        rzOut2_4->setObjectName(QString::fromUtf8("rzOut2_4"));
        rzOut2_4->setGeometry(QRect(167, 57, 50, 50));
        rzOut2_4->setMinimumSize(QSize(50, 50));
        rzOut2_4->setMaximumSize(QSize(50, 50));
        rzOut2_4->setFont(font5);
        rzOut2_4->setMaxLength(4);
        rzOut2_4->setFrame(true);
        rzOut2_4->setCursorPosition(0);
        rzOut2_4->setReadOnly(true);
        rzOut1_4 = new QLineEdit(rzOFrame4);
        rzOut1_4->setObjectName(QString::fromUtf8("rzOut1_4"));
        rzOut1_4->setGeometry(QRect(167, 2, 50, 50));
        rzOut1_4->setMinimumSize(QSize(50, 50));
        rzOut1_4->setMaximumSize(QSize(50, 50));
        rzOut1_4->setFont(font5);
        rzOut1_4->setMaxLength(4);
        rzOut1_4->setFrame(true);
        rzOut1_4->setCursorPosition(0);
        rzOut1_4->setReadOnly(true);
        rzOut4_2 = new QLineEdit(rzOFrame4);
        rzOut4_2->setObjectName(QString::fromUtf8("rzOut4_2"));
        rzOut4_2->setEnabled(false);
        rzOut4_2->setGeometry(QRect(57, 167, 50, 50));
        rzOut4_2->setMinimumSize(QSize(50, 50));
        rzOut4_2->setMaximumSize(QSize(50, 50));
        rzOut4_2->setFont(font4);
        rzOut4_2->setMaxLength(4);
        rzOut4_2->setFrame(true);
        rzOut4_2->setCursorPosition(0);
        rzOut4_2->setAlignment(Qt::AlignCenter);
        rzOut4_1 = new QLineEdit(rzOFrame4);
        rzOut4_1->setObjectName(QString::fromUtf8("rzOut4_1"));
        rzOut4_1->setEnabled(false);
        rzOut4_1->setGeometry(QRect(2, 167, 50, 50));
        rzOut4_1->setMinimumSize(QSize(50, 50));
        rzOut4_1->setMaximumSize(QSize(50, 50));
        rzOut4_1->setFont(font4);
        rzOut4_1->setMaxLength(4);
        rzOut4_1->setFrame(true);
        rzOut4_1->setCursorPosition(0);
        rzOut4_1->setAlignment(Qt::AlignCenter);
        rzOFrame5 = new QFrame(rzOFrame);
        rzOFrame5->setObjectName(QString::fromUtf8("rzOFrame5"));
        rzOFrame5->setGeometry(QRect(0, 0, 281, 281));
        rzOFrame5->setAutoFillBackground(false);
        rzOut4_5 = new QLineEdit(rzOFrame5);
        rzOut4_5->setObjectName(QString::fromUtf8("rzOut4_5"));
        rzOut4_5->setGeometry(QRect(222, 167, 50, 50));
        rzOut4_5->setMinimumSize(QSize(50, 50));
        rzOut4_5->setMaximumSize(QSize(50, 50));
        rzOut4_5->setFont(font5);
        rzOut4_5->setMaxLength(4);
        rzOut4_5->setFrame(true);
        rzOut4_5->setCursorPosition(0);
        rzOut4_5->setReadOnly(true);
        rzOut2_5 = new QLineEdit(rzOFrame5);
        rzOut2_5->setObjectName(QString::fromUtf8("rzOut2_5"));
        rzOut2_5->setGeometry(QRect(222, 57, 50, 50));
        rzOut2_5->setMinimumSize(QSize(50, 50));
        rzOut2_5->setMaximumSize(QSize(50, 50));
        rzOut2_5->setFont(font5);
        rzOut2_5->setMaxLength(4);
        rzOut2_5->setFrame(true);
        rzOut2_5->setCursorPosition(0);
        rzOut2_5->setReadOnly(true);
        rzOut1_5 = new QLineEdit(rzOFrame5);
        rzOut1_5->setObjectName(QString::fromUtf8("rzOut1_5"));
        rzOut1_5->setGeometry(QRect(222, 2, 50, 50));
        rzOut1_5->setMinimumSize(QSize(50, 50));
        rzOut1_5->setMaximumSize(QSize(50, 50));
        rzOut1_5->setFont(font5);
        rzOut1_5->setMaxLength(4);
        rzOut1_5->setFrame(true);
        rzOut1_5->setCursorPosition(0);
        rzOut1_5->setReadOnly(true);
        rzOut5_2 = new QLineEdit(rzOFrame5);
        rzOut5_2->setObjectName(QString::fromUtf8("rzOut5_2"));
        rzOut5_2->setEnabled(false);
        rzOut5_2->setGeometry(QRect(57, 222, 50, 50));
        rzOut5_2->setMinimumSize(QSize(50, 50));
        rzOut5_2->setMaximumSize(QSize(50, 50));
        rzOut5_2->setFont(font4);
        rzOut5_2->setMaxLength(4);
        rzOut5_2->setFrame(true);
        rzOut5_2->setCursorPosition(0);
        rzOut5_2->setAlignment(Qt::AlignCenter);
        rzOut5_5 = new QLineEdit(rzOFrame5);
        rzOut5_5->setObjectName(QString::fromUtf8("rzOut5_5"));
        rzOut5_5->setGeometry(QRect(222, 222, 50, 50));
        rzOut5_5->setMinimumSize(QSize(50, 50));
        rzOut5_5->setMaximumSize(QSize(50, 50));
        rzOut5_5->setFont(font5);
        rzOut5_5->setMaxLength(4);
        rzOut5_5->setFrame(true);
        rzOut5_5->setCursorPosition(0);
        rzOut5_5->setReadOnly(true);
        rzOut5_3 = new QLineEdit(rzOFrame5);
        rzOut5_3->setObjectName(QString::fromUtf8("rzOut5_3"));
        rzOut5_3->setEnabled(false);
        rzOut5_3->setGeometry(QRect(112, 222, 50, 50));
        rzOut5_3->setMinimumSize(QSize(50, 50));
        rzOut5_3->setMaximumSize(QSize(50, 50));
        rzOut5_3->setFont(font4);
        rzOut5_3->setMaxLength(4);
        rzOut5_3->setFrame(true);
        rzOut5_3->setCursorPosition(0);
        rzOut5_3->setAlignment(Qt::AlignCenter);
        rzOut5_1 = new QLineEdit(rzOFrame5);
        rzOut5_1->setObjectName(QString::fromUtf8("rzOut5_1"));
        rzOut5_1->setEnabled(false);
        rzOut5_1->setGeometry(QRect(2, 222, 50, 50));
        rzOut5_1->setMinimumSize(QSize(50, 50));
        rzOut5_1->setMaximumSize(QSize(50, 50));
        rzOut5_1->setFont(font4);
        rzOut5_1->setMaxLength(4);
        rzOut5_1->setFrame(true);
        rzOut5_1->setCursorPosition(0);
        rzOut5_1->setAlignment(Qt::AlignCenter);
        rzOut5_4 = new QLineEdit(rzOFrame5);
        rzOut5_4->setObjectName(QString::fromUtf8("rzOut5_4"));
        rzOut5_4->setEnabled(false);
        rzOut5_4->setGeometry(QRect(167, 222, 50, 50));
        rzOut5_4->setMinimumSize(QSize(50, 50));
        rzOut5_4->setMaximumSize(QSize(50, 50));
        rzOut5_4->setFont(font4);
        rzOut5_4->setMaxLength(4);
        rzOut5_4->setFrame(true);
        rzOut5_4->setCursorPosition(0);
        rzOut5_4->setAlignment(Qt::AlignCenter);
        rzOut3_5 = new QLineEdit(rzOFrame5);
        rzOut3_5->setObjectName(QString::fromUtf8("rzOut3_5"));
        rzOut3_5->setGeometry(QRect(222, 112, 50, 50));
        rzOut3_5->setMinimumSize(QSize(50, 50));
        rzOut3_5->setMaximumSize(QSize(50, 50));
        rzOut3_5->setFont(font5);
        rzOut3_5->setMaxLength(4);
        rzOut3_5->setFrame(true);
        rzOut3_5->setCursorPosition(0);
        rzOut3_5->setReadOnly(true);
        rzOFrame5->raise();
        rzOFrame4->raise();
        rzOFrame3->raise();
        rzOut2_2->raise();
        rzOut2_1->raise();
        rzOut1_2->raise();
        rzOut1_1->raise();
        rezLabel = new QLabel(rzvFrame);
        rezLabel->setObjectName(QString::fromUtf8("rezLabel"));
        rezLabel->setGeometry(QRect(760, 0, 241, 31));
        rezLabel->setFont(font1);
        backButt = new QPushButton(rzvFrame);
        backButt->setObjectName(QString::fromUtf8("backButt"));
        backButt->setGeometry(QRect(930, 360, 91, 31));
        line_2 = new QFrame(rzvFrame);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(670, 180, 70, 3));
        line_2->setStyleSheet(QString::fromUtf8("background:rgb(0, 0, 0)"));
        line_2->setLineWidth(2);
        line_2->setMidLineWidth(0);
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line = new QFrame(rzvFrame);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(670, 162, 70, 3));
        line->setStyleSheet(QString::fromUtf8("background:rgb(0, 0, 0)"));
        line->setLineWidth(2);
        line->setMidLineWidth(0);
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(rzvFrame);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(300, 170, 65, 3));
        line_3->setStyleSheet(QString::fromUtf8("background:rgb(0, 0, 0)"));
        line_3->setLineWidth(2);
        line_3->setMidLineWidth(0);
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        clearAllButton = new QPushButton(centralwidget);
        clearAllButton->setObjectName(QString::fromUtf8("clearAllButton"));
        clearAllButton->setGeometry(QRect(420, 10, 80, 21));
        clearAllButton->setStyleSheet(QString::fromUtf8("background: rgb(200, 0, 3)"));
        MainWindow->setCentralWidget(centralwidget);
        listWidget->raise();
        rzvFrame->raise();
        mainFrame->raise();
        mSizeSlider->raise();
        label->raise();
        pushButton->raise();
        inpLabel->raise();
        pushButton_2->raise();
        slidertxtFrame->raise();
        ijframe->raise();
        saveMatr->raise();
        ijElemInp->raise();
        readyBut->raise();
        ijSaveBut->raise();
        ijButton->raise();
        ijOutBut->raise();
        ijElemOut->raise();
        raznBut->raise();
        ravnBut->raise();
        clearAllButton->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1129, 20));
        menu = new QMenu(menubar);
        menu->setObjectName(QString::fromUtf8("menu"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menu->menuAction());

        retranslateUi(MainWindow);
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), inpLabel, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), pushButton, SLOT(show()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), pushButton_2, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), mSizeSlider, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), slidertxtFrame, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), ijframe, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), raznBut, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), ravnBut, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), ijButton, SLOT(hide()));
        QObject::connect(listWidget, SIGNAL(currentItemChanged(QListWidgetItem*,QListWidgetItem*)), ijOutBut, SLOT(hide()));

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Triangle Matrix", nullptr));

        const bool __sortingEnabled = listWidget->isSortingEnabled();
        listWidget->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listWidget->item(0);
        ___qlistwidgetitem->setText(QCoreApplication::translate("MainWindow", "\320\222\320\262\320\276\320\264 \320\274\320\260\321\202\321\200\320\270\321\206\321\213", nullptr));
        QListWidgetItem *___qlistwidgetitem1 = listWidget->item(1);
        ___qlistwidgetitem1->setText(QCoreApplication::translate("MainWindow", "   \320\222\320\262\320\276\320\264 \320\274\321\213\321\202\321\200\320\270\321\206\321\213 \320\277\320\276\320\273\320\275\320\276\321\201\321\202\321\214\321\216", nullptr));
        QListWidgetItem *___qlistwidgetitem2 = listWidget->item(2);
        ___qlistwidgetitem2->setText(QCoreApplication::translate("MainWindow", "   \320\222\320\262\320\265\321\201\321\202\320\270 \320\267\320\275\320\260\321\207\320\265\320\275\320\270\320\265 \321\215\320\273\320\265\320\274\320\265\320\275\321\202\320\260 \320\274\320\260\321\202\321\200\320\270\321\206\321\213  \321\201 \320\270\320\275\320\264\320\265\320\272\321\201\320\260\320\274\320\270 i, j", nullptr));
        QListWidgetItem *___qlistwidgetitem3 = listWidget->item(3);
        ___qlistwidgetitem3->setText(QCoreApplication::translate("MainWindow", "\320\222\321\213\320\262\320\276\320\264 \320\274\320\260\321\202\321\200\320\270\321\206\321\213", nullptr));
        QListWidgetItem *___qlistwidgetitem4 = listWidget->item(4);
        ___qlistwidgetitem4->setText(QCoreApplication::translate("MainWindow", "   \320\222\321\213\320\262\320\276\320\264 \320\274\320\260\321\202\321\200\320\270\321\206\321\213 \320\277\320\276\320\273\320\275\320\276\321\201\321\202\321\214\321\216", nullptr));
        QListWidgetItem *___qlistwidgetitem5 = listWidget->item(5);
        ___qlistwidgetitem5->setText(QCoreApplication::translate("MainWindow", "   \320\222\321\213\320\262\320\265\321\201\321\202\320\270 \320\267\320\275\320\260\321\207\320\265\320\275\320\270\320\265 \321\215\320\273\320\265\320\274\320\265\320\275\321\202\320\260 \320\274\320\260\321\202\321\200\320\270\321\206\321\213  \321\201 \320\270\320\275\320\264\320\265\320\272\321\201\320\260\320\274\320\270 i, j", nullptr));
        QListWidgetItem *___qlistwidgetitem6 = listWidget->item(6);
        ___qlistwidgetitem6->setText(QCoreApplication::translate("MainWindow", "\320\240\320\260\320\267\320\275\320\276\321\201\321\202\321\214 \320\264\320\262\321\203\321\205 \321\202\321\200\320\265\321\203\320\263\320\276\320\273\321\214\320\275\321\213\321\205 \320\274\320\260\321\202\321\200\320\270\321\206", nullptr));
        QListWidgetItem *___qlistwidgetitem7 = listWidget->item(7);
        ___qlistwidgetitem7->setText(QCoreApplication::translate("MainWindow", "\320\237\321\200\320\276\320\262\320\265\321\200\320\272\320\260 \321\200\320\260\320\262\320\265\320\275\321\201\321\202\320\262\320\260 \320\264\320\262\321\203\321\205 \320\274\320\260\321\202\321\200\320\270\321\206", nullptr));
        QListWidgetItem *___qlistwidgetitem8 = listWidget->item(8);
        ___qlistwidgetitem8->setText(QCoreApplication::translate("MainWindow", "\320\227\320\260\320\277\320\270\321\201\321\214 \320\274\320\260\321\202\321\200\320\270\321\206\321\213 \320\262 \321\204\320\260\320\271\320\273", nullptr));
        QListWidgetItem *___qlistwidgetitem9 = listWidget->item(9);
        ___qlistwidgetitem9->setText(QCoreApplication::translate("MainWindow", "\320\247\321\202\320\265\320\275\320\270\320\265 \320\274\320\260\321\202\321\200\320\270\321\206\321\213 \320\270\320\267 \321\202\320\265\320\272\321\201\321\202\320\276\320\262\320\276\320\263\320\276 \321\204\320\260\320\271\320\273\320\260", nullptr));
        listWidget->setSortingEnabled(__sortingEnabled);

        label->setText(QCoreApplication::translate("MainWindow", "\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \320\264\320\265\320\271\321\201\321\202\320\262\320\270\320\265", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "\320\222\321\213\320\261\321\200\320\260\321\202\321\214", nullptr));
        inpLabel->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aa0000;\">\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\200\320\260\320\267\320\274\320\265\321\200 \320\274\320\260\321\202\321\200\320\270\321\206\321\213</span></p></body></html>", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "\320\224\320\260\320\273\320\265\320\265", nullptr));
        mInp2_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp2_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp1_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp1_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp2_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp2_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp1_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp1_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp2_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp2_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp1_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp1_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp3_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp3_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp3_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp3_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp3_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp3_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp4_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp4_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp3_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp3_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp4_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp4_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp2_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp2_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp1_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp1_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp4_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp4_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp4_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp4_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp4_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp4_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp2_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp2_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp1_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp1_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp5_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp5_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp5_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp5_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp5_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp5_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp5_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp5_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp5_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp5_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        mInp3_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        mInp3_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        inpLabel_5->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">2</span></p></body></html>", nullptr));
        inpLabel_4->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">4</span></p></body></html>", nullptr));
        inpLabel_3->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">3</span></p></body></html>", nullptr));
        inpLabel_2->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">5</span></p></body></html>", nullptr));
#if QT_CONFIG(tooltip)
        mSizeSlider->setToolTip(QString());
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        mSizeSlider->setStatusTip(QString());
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        mSizeSlider->setWhatsThis(QString());
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        mSizeSlider->setAccessibleName(QString());
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        mSizeSlider->setAccessibleDescription(QString());
#endif // QT_CONFIG(accessibility)
        label_2->setText(QCoreApplication::translate("MainWindow", "\320\222\320\262\320\265\320\264\320\270\321\202\320\265 \320\270\320\275\320\264\320\265\320\272\321\201\321\213", nullptr));
        spinBoxI->setSuffix(QString());
        spinBoxI->setPrefix(QCoreApplication::translate("MainWindow", "i:", nullptr));
        spinBoxJ->setSuffix(QString());
        spinBoxJ->setPrefix(QCoreApplication::translate("MainWindow", "j:", nullptr));
        saveMatr->setText(QCoreApplication::translate("MainWindow", "\320\241\320\276\321\205\321\200\320\260\320\275\320\270\321\202\321\214", nullptr));
        ijElemInp->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        readyBut->setText(QCoreApplication::translate("MainWindow", "\320\223\320\276\321\202\320\276\320\262\320\276", nullptr));
        ijSaveBut->setText(QCoreApplication::translate("MainWindow", "\320\241\320\276\321\205\321\200\320\260\320\275\320\270\321\202\321\214", nullptr));
        ijButton->setText(QCoreApplication::translate("MainWindow", "\320\224\320\260\320\273\320\265\320\265", nullptr));
        ijOutBut->setText(QCoreApplication::translate("MainWindow", "\320\224\320\260\320\273\320\265\320\265", nullptr));
        ijElemOut->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        ijElemOut->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        raznBut->setText(QCoreApplication::translate("MainWindow", "\320\224\320\260\320\273\320\265\320\265", nullptr));
        ravnBut->setText(QCoreApplication::translate("MainWindow", "\320\224\320\260\320\273\320\265\320\265", nullptr));
        rzInp2_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_12->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_12->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_22->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_22->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_22->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_22->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_12->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_12->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_32->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_32->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_32->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_32->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_22->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_22->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_12->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_12->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_32->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_32->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_32->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_32->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_42->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_42->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_42->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_42->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_42->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_42->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_42->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_42->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_22->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_22->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_12->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_12->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp4_52->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp4_52->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp2_52->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp2_52->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp1_52->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp1_52->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_22->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_22->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_52->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_52->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_32->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_32->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_12->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_12->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp5_42->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp5_42->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzInp3_52->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzInp3_52->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "\320\222\320\262\320\265\320\264\320\270\321\202\320\265 \321\215\320\273-\321\202\321\213 \320\274\320\260\321\202\321\200\320\270\321\206\321\213 2:", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "\320\222\320\262\320\265\320\264\320\270\321\202\320\265 \321\215\320\273-\321\202\321\213 \320\274\320\260\321\202\321\200\320\270\321\206\321\213 1:", nullptr));
        rzBut->setText(QCoreApplication::translate("MainWindow", "\320\222\321\213\321\207\320\270\321\201\320\273\320\270\321\202\321\214", nullptr));
        rvBut->setText(QCoreApplication::translate("MainWindow", "\320\237\321\200\320\276\320\262\320\265\321\200\320\270\321\202\321\214", nullptr));
        rvLabel->setText(QCoreApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0206;\">\320\234\320\260\321\202\321\200\320\270\321\206\321\213 \320\240\320\260\320\262\320\275\321\213</span></p></body></html>", nullptr));
        rzOut2_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut2_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut1_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut1_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut2_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut2_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut1_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut1_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut2_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut2_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut1_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut1_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut3_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut3_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut3_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut3_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut3_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut3_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut4_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut4_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut3_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut3_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut4_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut4_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut2_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut2_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut1_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut1_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut4_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut4_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut4_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut4_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut4_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut4_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut2_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut2_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut1_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut1_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut5_2->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut5_2->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut5_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut5_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut5_3->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut5_3->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut5_1->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut5_1->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut5_4->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut5_4->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rzOut3_5->setInputMask(QCoreApplication::translate("MainWindow", "####", nullptr));
        rzOut3_5->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        rezLabel->setText(QCoreApplication::translate("MainWindow", "\320\240\320\265\320\267\321\203\320\273\321\214\321\202\320\260\321\202 \320\262\321\213\321\207\320\270\321\202\320\260\320\275\320\270\321\217:", nullptr));
        backButt->setText(QCoreApplication::translate("MainWindow", "\320\235\320\260\320\267\320\260\320\264", nullptr));
        clearAllButton->setText(QCoreApplication::translate("MainWindow", "\320\241\320\261\321\200\320\276\321\201 \320\264\320\260\320\275\320\275\321\213\321\205", nullptr));
        menu->setTitle(QCoreApplication::translate("MainWindow", "\320\244\320\260\320\271\320\273", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
